### ISSUE TITLE
Menu Separators No Longer Working

### ISSUE THREAD

**Issue by tibmeister** [vaniacer/sshto#14]
I just reloaded one of my machines and did a fresh clone of the repo.  Using the same config file as before, the updated version of the script no longer seems to honor the #Host DUMMY #SiteName# moniker anymore, it just shows all hosts in a single, large list.

**Comment by girls-whocode** [comment]
I thought I would answer your question since I experienced the same issue. Place a line separator in between them... Like so:

```sh
#Host Dummy #Switches and Routers#

Host asus router #Asus AX Router
```

For mine, I changed dummy to groups, because I didn't think dummy was appropriate. To do that, open the sshto.sh file and go to about line number 565, (or search for dummy), and change:

```
strt && host == "dummy"{
    hostname=$2
    print "group_name", "dummy", desc
    strt=0
}

```

to 

```
strt && host == "groups"{
    hostname=$2
    print "group_name", "groups", desc
    strt=0
}

```

**Comment by vaniacer** [comment]
I believe this is fixed in recent updates. I've also made it easier to change group separator template in this [update](https://github.com/vaniacer/sshto/commit/74ab99c118f31203e2b2638a4c69b1833b8c429e)
thanks
